name: Test Configuration
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Install XEEPROMConfig lib
        run: platformio lib --global install https://github.com/reivaxy/XEEPROMConfig
        working-directory: handMonitor
      - name: Install NTPClient lib
        run: platformio lib --global install https://github.com/arduino-libraries/NTPClient
        working-directory: handMonitor  
      - name: Build
        run: platformio run
        working-directory: handMonitor
